[package]
name = "tempo-bench"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
tempo-chainspec.workspace = true
tempo-evm.workspace = true
tempo-precompiles.workspace = true
tempo-contracts.workspace = true
# Workspace dependencies
alloy = { workspace = true, features = [
  "genesis",
  "signers",
  "signer-local",
  "network",
  "sol-types",
] }
alloy-consensus = { workspace = true, features = ["secp256k1"] }
clap = { workspace = true, features = ["derive", "env"] }
eyre.workspace = true
hex.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
reth-chainspec.workspace = true
reth.workspace = true
reth-evm.workspace = true


# Bespoke dependencies
alloy-signer-local = { version = "1", features = ["mnemonic"] }
core_affinity = "0.8.3"
crossbeam-utils = "0.8.21"
dashmap = "6.1"
fastrand = "2.1"
http = "1"
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
mimalloc = "0.1.47"
parking_lot = "0.12.4"
ratelimit = "0.10"
rayon = "1.10"
rlimit = "0.10.2"
simple-tqdm = { version = "0.2.0", features = ["rayon"] }
thousands = "0.2.0"
